language: node_js
node_js:
  - "8"
dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install -g grunt-cli bower
  
build:
  - bower install 
  - grunt build

before_deploy:
  - cd build
  
deploy:
  provider: azure_web_apps
