version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # keep container running
    #command: