name: Build campus API docker image

on:
  push:
    branches:
      - fix-tg-login
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          logout: true

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          repository: ${{ github.repository }}

      - name: Build Docker image
        run: |          
          now=$(date +%Y%m%d%H%M%S)          
          image="kpiua/ecampus-kpi-ua:ui-$now"
          docker build ./ --file ./.dockerfile --tag $image
          docker push $image